### ISSUE TITLE
Photo Channel missing from WAD list in guide generated

### ISSUE THREAD

**Issue by infopcgood** [modmii/modmii.github.io#14]
**What should happen**: Choosing to install the Photo Channel in the ModMii wizard should add an extra WAD called `Photo-Channel-1.0-NUS-v2.wad` to the WAD list in the ModMii Wizard Guide (at the bottom of section III-5), making the total length of the list 46.
**What actually happened**: Even when I chose to install the Photo Channel, it didn't appear at the WAD list.
**Possible fix**: When Photo Channel is selected to be installed, add it to the WAD list.

**Additional Information**: This is the WAD list I got. I chose to install Mii Channel and Photo Channel, excluding the Wii Shop.
```
1. cIOS248[38]-d2x-v11-beta1
2. cIOS249[56]-d2x-v11-beta1
3. cIOS250[57]-d2x-v11-beta1
4. cIOS251[58]-d2x-v11-beta1
5. IOS11v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
6. IOS12-64-v526
7. IOS13-64-v1032
8. IOS14-64-v1032
9. IOS15-64-v1032
10. IOS17-64-v1032
11. IOS20v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
12. IOS21-64-v1039
13. IOS22-64-v1294
14. IOS28-64-v1807
15. IOS30v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
16. IOS31-64-v3608
17. IOS33-64-v3608
18. IOS34-64-v3608
19. IOS35-64-v3608
20. IOS36-64-v3608
21. IOS37-64-v5663
22. IOS38-64-v4124
23. IOS40v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
24. IOS41-64-v3607
25. IOS43-64-v3607
26. IOS45-64-v3607
27. IOS46-64-v3607
28. IOS48-64-v4124
29. IOS50v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
30. IOS52v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
31. IOS53-64-v5663
32. IOS55-64-v5663
33. IOS56-64-v5662
34. IOS57-64-v5919
35. IOS58-64-v6176
36. IOS60v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
37. IOS61-64-v5662
38. IOS62-64-v6430
39. IOS70v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
40. IOS80v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
41. IOS9-64-v1034
42. Mii-Channel-NUS-v6
43. Open_HBC_1.1.5_LULZ
44. RVL-mios-v10
45. USBLoader(s)-ahbprot58-SD-USB-v14-IDCL (see spoiler for boot info)
```

**Comment by xflak** [comment]
What specific parameters was your guide built using?

I double checked and the WAD "Photo-Channel-1.1-NUS-v3" is included in the list as per the below.

This _list_ was generated using the following parameters:
- Install and\or update all recommended softmods
- Current System Menu is 4.2U
- Desired System Menu is 4.2U
- Update active IOSs (can be disabled in options)
- Do not install a cMIOS (can be enabled in options)
- Do not install Hermes cIOSs (can be enabled in options)
- Install a USB-Loader Forwarder Channel (can be disabled in options)
- Install Extra Brick Protection (patched IOS60 in unused system menu IOS slots) (can be disabled in options)
- Install Photo Channel
- Install Mii Channel

1. cIOS248[38]-d2x-v11-beta1
2. cIOS249[56]-d2x-v11-beta1
3. cIOS250[57]-d2x-v11-beta1
4. cIOS251[58]-d2x-v11-beta1
5. IOS11v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
6. IOS12-64-v526
7. IOS13-64-v1032
8. IOS14-64-v1032
9. IOS15-64-v1032
10. IOS17-64-v1032
11. IOS20v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
12. IOS21-64-v1039
13. IOS22-64-v1294
14. IOS28-64-v1807
15. IOS30v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
16. IOS31-64-v3608
17. IOS33-64-v3608
18. IOS34-64-v3608
19. IOS35-64-v3608
20. IOS36-64-v3608
21. IOS37-64-v5663
22. IOS38-64-v4124
23. IOS40v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
24. IOS41-64-v3607
25. IOS43-64-v3607
26. IOS45-64-v3607
27. IOS46-64-v3607
28. IOS48-64-v4124
29. IOS50v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
30. IOS52v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
31. IOS53-64-v5663
32. IOS55-64-v5663
33. IOS56-64-v5662
34. IOS57-64-v5919
35. IOS58-64-v6176
36. IOS60v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
37. IOS61-64-v5662
38. IOS62-64-v6430
39. IOS70v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
40. IOS80v65535(IOS60v6174[FS-ES-NP-VP-DIP-RC24])
41. IOS9-64-v1034
42. Mii-Channel-NUS-v6
43. Open_HBC_1.1.5_LULZ
**44. Photo-Channel-1.1-NUS-v3**
45. RVL-mios-v10
46. USBLoader(s)-ahbprot58-SD-USB-v14-IDCL (see spoiler for boot info)

I understand that there are other issues surrounding Photo Channel 1.1 where it requires a HAZA channel ID otherwise photo channel 1.0 is launched but that's a separate thing.

If you can share with the specific parameters to replicate the issue I'll double check again under those conditions, otherwise I'll be closing this issue shortly, thanks.

**Comment by xflak** [comment]
I think I see what you're referring to, did you choose Korean as your region and are expecting to find Photo-Channel-1.0-NUS-v2 in your list?

Thanks for reporting, it's already fixed in my beta, but I may be releasing a small bugfix update before any big updates and will make sure this is included.
