### ISSUE TITLE
Does not use configured proxy

### ISSUE THREAD

**Issue by eku** [modmii/modmii.github.io#3]
ModMii does not work behind a proxy, because it establishes connections to the Internet directly instead of considering the system settings for Internet connections

**Comment by xflak** [comment]
** Proxy Support ** (steps shared by Wiimm)
Because of using wget, ModMii is able to use http and ftp proxies. Just setup the variables http_proxy and ftp_proxy in your user environment and/or system environment. You can set the variables of both levels if you are opening "System Settings | System | Extended Settings | Environment Variables"
If your proxy server has IP 1.2.3.4 and use port 3128, then set:
http_proxy=http://1.2.3.4:3128
ftp_proxy=http://1.2.3.4:3128
Instead of the IP, a DNS name is also possible.

**Comment by eku** [comment]
> You can set the variables of both levels if you are opening "System Settings | System | Extended Settings | Environment Variables"

So it is not enough to define a proxy under Internet settings, but one must define environment variables as well. That is unexpected.

Can Modmii read the Internet settings an call `wget` with the environment variables set?

**Comment by eku** [comment]
I've just noticed, that the search for cIOS updates on GitHub bypasses the proxy even when the mentioned environment settings are done.
